feat: wildcard for fetching all secrets
hashicorp/vault-action pull request #247
Opened 2021-08-26 15:53 UTC by matryxxx02

fixes #234 

This PR allows the use of * (wildcard) to fetch all secrets into env variables.

# Example Usage  

example of secrets :
```json 
{
 ci : {
   aws : {
     URL_API : {
        "http://localhost:3000"
     }
   }
 }
}
```

```yaml
jobs:
    build:
        # ...
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2.3.1
              with:
                url: https://vault.mycompany.com:8200
                token: ${{ secrets.VaultToken }}
                caCertificate: ${{ secrets.VAULTCA }}
                secrets: |
                    secret/data/ci/aws *
            # ...
           - name : Test secret
              run: echo "Hello ${{env.URL_API}}"
```

2021-11-12 21:07 UTC, bfaulk96 commented
This would be great!

2021-11-23 21:17 UTC, bfaulk96 commented
@matryxxx02 any chance you could resolve those merge conflicts?

2021-11-23 21:42 UTC, bfaulk96 commented
Dang, that was fast!! @doowb What are the chances of this landing in the next release?

2021-12-22 17:28 UTC, ElenaForester commented
Eagerly waiting for this to be released 🙏

2021-12-29 14:33 UTC, karlanuetzel commented
+1 on this landing in next release

2022-01-20 03:38 UTC, ndrader commented
Any news on this getting merged? Would love to use it.

2022-01-25 23:16 UTC, ElenaForester commented
> Any news on this getting merged? Would love to use it.

I figured out that for now you can use 

> ```yaml
> secrets: |
>                     secret/data/ci/aws $.$
> ```

2022-02-08 09:22 UTC, Marcanta commented
> > Any news on this getting merged? Would love to use it.
> 
> I figured out that for now you can use
> 
> > ```yaml
> > secrets: |
> >                     secret/data/ci/aws $.$
> > ```

I agree, however, it's annoying to use...

```yml
      - name: Import env.TEST from vault
        uses: hashicorp/vault-action@v2.3.0
        with:
          url: http://127.0.0.1:8200
          tlsSkipVerify: true
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              secret/data/test $.$ | TEST
              
      - name : echo env
        run: echo "Hello ${{env.TEST.HELLO_WORLD}}"
```

It would be great if we could drop the `TEST`.

2022-08-26 20:47 UTC, karlanuetzel commented
Any update on this?

2022-10-13 22:32 UTC, hsimon-hashicorp commented
> Currently going on `1 year, 47 days, 21 hours, 50 minutes` since this great PR was created and subsequently ignored.

You're right, and you have my apologies as well as my thanks for resurfacing this. I'll have our engineering team take a look. :)

2022-10-14 13:20 UTC, bfaulk96 commented
@matryxxx02 looks like there are once again a few merge conflicts, if you have time to address them

2023-01-19 17:12 UTC, ltcarbonell requested changes
Good work so far, just a couple possible issues I noticed.  Thank you for sticking with this, I do think that this is a good feature we would want to include.

2023-01-19 17:12 UTC, ltcarbonell commented on src/secrets.js
> +        let value;
I believe we will need to pull out [this](https://github.com/hashicorp/vault-action/pull/247/files#diff-47be61e4446c15650db3c077e509c50ccfa2b4626c65fe43bad550fe25e611a9L53) JSON parse and move it here

2023-01-19 17:29 UTC, ltcarbonell commented on src/action.js
> +function addMask(value) {
I think moving this to its own function is a good idea, however it seems to cause some issues with the acceptance tests

```
~$ npm run test

> vault-action@0.1.0 test
> jest

 PASS  src/auth.test.js
 FAIL  src/action.test.js
  ● exportSecrets › single-line secret gets masked

    expect(jest.fn()).toBeCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 2

      334 |         await exportSecrets();
      335 |
    > 336 |         expect(command.issue).toBeCalledTimes(1);
          |                               ^
      337 |
      338 |         expect(command.issue).toBeCalledWith('add-mask', 'secret');
      339 |         expect(core.setOutput).toBeCalledWith('key', 'secret');

      at Object.toBeCalledTimes (src/action.test.js:336:31)

  ● exportSecrets › multi-line secret gets masked for each line

    expect(jest.fn()).toBeCalledTimes(expected)

    Expected number of calls: 2
    Received number of calls: 4

      354 |         await exportSecrets();
      355 |
    > 356 |         expect(command.issue).toBeCalledTimes(2); // 1 for each non-empty line.
          |                               ^
      357 |
      358 |         expect(command.issue).toBeCalledWith('add-mask', 'a multi-line string');
      359 |         expect(command.issue).toBeCalledWith('add-mask', 'with blank lines');

      at Object.toBeCalledTimes (src/action.test.js:356:31)

::add-mask::value
::add-mask::value
 PASS  src/retries.test.js

Test Suites: 1 failed, 2 passed, 3 total
Tests:       2 failed, 27 passed, 29 total
Snapshots:   0 total
Time:        2.532 s, estimated 3 s
Ran all test suites.
::add-mask::value
::add-mask::value
```

2023-09-15 13:37 UTC, maxcoulombe commented
Hey everyone, thanks for showing interest in this feature. I'm happy to report that an equivalent implementation was recently merged in #488 . I'll close this PR for now as the functionality implemented appears equivalent.

The wildcard selector feature should be available in an up-coming v2.8.0 release, cheers!

2023-09-15 13:37 UTC, closed without merging