Test that overwrite env var works in nested action
hashicorp/vault-action pull request #453
Opened 2023-04-29 00:59 UTC by leonardovillela

### Description 📜 

This PR introduces changes to add an E2E test to verify if it's possible to overwrite env vars value set before in a nested action. [This test](https://github.com/hashicorp/vault-action/issues/350) is nice to ensure we do not introduce this bug again as a regression in the future.

Closes https://github.com/hashicorp/vault-action/issues/350

`cc:` @Zlaticanin

2023-04-29 00:59 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/vault-action?pullRequest=453)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/vault-action?pullRequest=453)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/vault-action?pullRequest=453).</sub>

2023-05-04 22:02 UTC, thyton commented
Hey @leonardovillela, thanks for taking this on! 
Based on [the PR original issue](https://github.com/hashicorp/vault-action/issues/350), the expected behavior is described as the env var should have the new value after a subsequent call to vault-action. Perhaps, a simple enough approach to testing it could be the following. We don't need a separate action file for this approach.
- Creating another endpoint to `secret/data` that has a different `secret` value 
```
await got(`http://${vaultUrl}/v1/secret/data/subsequent-test`, {
            method: 'POST',
            headers: {
                'X-Vault-Token': vaultToken,
            },
            json: {
                data: {
                    secret: 'SUBSEQUENT_TEST_SECRET',
                },
            },
        });
```

- Calling vault-action twice and reading `secret/data/test` and  the new endpoint subsequently
```
- name: Test Vault Action Overwrites Env Vars In Subsequent Action (part 1/2)
      uses: ./
      with:
        url: http://localhost:8200/
        token: testtoken
        secrets: |
          secret/data/test secret | SUBSEQUENT_TEST_SECRET;
- name: Test Vault Action Overwrites Env Vars In Subsequent Action (part 2/2)
      uses: ./
      with:
        url: http://localhost:8200/
        token: testtoken
        secrets: |
          secret/data/subsequent-test secret | SUBSEQUENT_TEST_SECRET;
```

2023-05-05 16:24 UTC, thyton reviewed
Hey @leonardovillela, thanks for taking this on!
Based on https://github.com/hashicorp/vault-action/issues/350, the expected behavior is described as the env var should have the new value after a subsequent call to vault-action. Perhaps, a simple enough approach to testing it could be the following. We don't need a separate action file for this approach.
- Creating another endpoint to `secret/data` that has a different `secret` value 
```
await got(`http://${vaultUrl}/v1/secret/data/subsequent-test`, {
            method: 'POST',
            headers: {
                'X-Vault-Token': vaultToken,
            },
            json: {
                data: {
                    secret: 'SUBSEQUENT_TEST_SECRET',
                },
            },
        });
```

- Calling vault-action twice and reading `secret/data/test` and  the new endpoint subsequently
```
- name: Test Vault Action Overwrites Env Vars In Subsequent Action (part 1/2)
      uses: ./
      with:
        url: http://localhost:8200/
        token: testtoken
        secrets: |
          secret/data/test secret | SUBSEQUENT_TEST_SECRET;
- name: Test Vault Action Overwrites Env Vars In Subsequent Action (part 2/2)
      uses: ./
      with:
        url: http://localhost:8200/
        token: testtoken
        secrets: |
          secret/data/subsequent-test secret | SUBSEQUENT_TEST_SECRET;
```

2023-05-06 22:16 UTC, leonardovillela commented
Hi @thyton, thanks for your review 🙇 

> Based on https://github.com/hashicorp/vault-action/issues/350, the expected behavior is described as the env var should have the new value after a subsequent call to vault-action.

On #350 the scenario described include also a new action that calls the `vault-action`, I tried to reproduce the exactly same scenario mentioned in the issue. But probably having this new action does not make that big difference, so I implemented your suggestion in https://github.com/hashicorp/vault-action/pull/453/commits/1d5aa91090953c29aff94d73ed48ce43b401695b

2023-05-11 18:00 UTC, thyton requested changes

2023-05-20 00:53 UTC, thyton approved these changes

2023-05-20 00:54 UTC, merged